[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[alias]
run-kernel = "run --package walros-kernel --target=x86_64-unknown-none"
build-kernel = "+nightly build --package walros-kernel --target=x86_64-kernel.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"